# -*- coding: utf-8 -*-
"""Logic Building Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hi6iI1m4IHwwlPqy4P86dwayCjJi2pLS
"""

# Task 1: User Login Check

# Given credentials
username = "admin"
password = "1234"

# Input from user (for real-world scenario)
entered_username = input("Enter Username: ")
entered_password = input("Enter Password: ")

# Checking credentials
if entered_username == username and entered_password == password:
    print("Login Successful")
else:
    print("Invalid Credentials")

# -------------------------------
# Task 2: Pass / Fail Analyzer
# -------------------------------

marks = [45, 78, 90, 33, 60]

pass_count = 0
fail_count = 0

for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1

print("Total Students:", len(marks))
print("Total Passed:", pass_count)
print("Total Failed:", fail_count)

# -------------------------------
# Task 3: Simple Data Cleaner
# -------------------------------

names = [" Alice ", "bob", " CHARLIE "]

cleaned_names = []

for name in names:
    cleaned_name = name.strip().lower()   # Remove spaces & convert to lowercase
    cleaned_names.append(cleaned_name)

print("Cleaned Names List:", cleaned_names)

# -------------------------------
# Task 4: Message Length Analyzer
# -------------------------------

messages = ["Hi", "Welcome to the platform", "OK"]

for message in messages:
    length = len(message)
    print(f"Message: '{message}' | Length: {length}")

    if length > 10:
        print(" This message is longer than 10 characters")

# -------------------------------
# Task 5: Error Message Detector
# -------------------------------

logs = ["INFO", "ERROR", "WARNING", "ERROR"]

error_count = 0

for log in logs:
    if log == "ERROR":
        error_count += 1

print("Total ERROR Messages:", error_count)